// Code generated by goctl. DO NOT EDIT.
package types

type ResponseBsee struct {
	Code  int         `json:"code"`
	Error string      `json:"error"`
	Data  interface{} `json:"data"`
}

type UserInfoRequest struct {
	UserId string `json:"userId"`
}

type UserInfoResponse struct {
	UserId   string `json:"userId"`
	UserName string `json:"username"`
}
