// Code generated by goctl. DO NOT EDIT.
package types

type ResponseBsee struct {
	Code uint32      `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UserInfoRequest struct {
	UserId string `json:"userId"`
}

type UserInfoResponse struct {
	UserId   string `json:"userId"`
	UserName string `json:"username"`
}
